# Generated by Django 5.1.2 on 2024-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('house_name', models.CharField(max_length=256)),
                ('street_name', models.CharField(max_length=256)),
                ('city_name', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('pincode', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
