# Generated by Django 5.1.2 on 2024-10-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_app', '0001_initial'),
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='log_reg_app.usertable'),
        ),
    ]
