# Generated by Django 5.1.2 on 2024-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertable',
            options={},
        ),
        migrations.AlterModelTable(
            name='usertable',
            table='user_detail',
        ),
    ]
