# Generated by Django 5.1.2 on 2024-10-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_alter_usertable_options_alter_usertable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
