# Generated by Django 5.1.2 on 2024-10-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_usertable_is_blocked_usertable_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='cart_id',
        ),
    ]
