# Generated by Django 5.1.2 on 2024-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('added_time', models.TimeField()),
                ('is_whishlisted', models.BooleanField()),
            ],
        ),
    ]
