# Generated by Django 5.1.2 on 2024-10-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carttable',
            table='table_cart',
        ),
    ]
