# Generated by Django 5.1.2 on 2024-10-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytable',
            old_name='image',
            new_name='category_image',
        ),
    ]
